______________________________________________________________________________________________________
______________________________________________________________________________________________________

In [67]:
#Code for Method 1:
def multiply(A,B):
    ans = [[0 for i in range(len(B))] for j in range(len(A[0]))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                ans[i][j] += A[i][k] * B[k][j]
    return ans

def inverse(matrix):
    import numpy as np
    try:
        i=np.linalg.inv(matrix)
        return i
    except:
        print("Inverse of the given matrix not possible")

def exponentOfMatrix(matrix,m):
    if m<0:
        answer=[[0 if i!=j else 1 for i in range(len(matrix))] for j in range(len(matrix))]
        for i in range(abs(m)):
            answer=multiply(answer,matrix)
        return inverse(matrix)
    else:
        answer=[[0 if i!=j else 1 for i in range(len(matrix))] for j in range(len(matrix))]
        for i in range(abs(m)):
            answer=multiply(answer,matrix)
        return answer
        
    

try:
    n=int(input("Enter the order of matrix: "))
    matrix=([ print("enter " +str(j)+"th row elements (use spaces between two elements)") 
             or [int(i) for i in input().split() ]  for j in range(n)])
    m=int(input("Enter the power "))
    answer=exponentOfMatrix(matrix,m)
    print(answer)
except:
    print("Invalid input given, please try again")


Enter the order of matrix:  3
enter 0th row elements (use spaces between two elements)
12 7 3
enter 1th row elements (use spaces between two elements)
4 5 6
enter 2th row elements (use spaces between two elements)
7 8 9
Enter the power 3
[[3623, 2906, 2382], [2396, 2043, 1800], [3842, 3258, 2853]]


______________________________________________________________________________________________________
______________________________________________________________________________________________________

In [83]:
#Code for Method 2:

def multiply(A,B):
    if tuple([A,B]) in hm:
        return hm[tuple([A,B])]
    ans = [[0 for i in range(len(B))] for j in range(len(A[0]))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                ans[i][j] += A[i][k] * B[k][j]
    hm[tuple([A,B])]=ans
    return ans

def inverse(matrix):
    import numpy as np
    try:
        i=np.linalg.inv(matrix)
        return i
    except:
        print("Inverse of the given matrix not possible")


def exponentOfMatrix(matrix,m):
    
    if m<0:
        m=-1*m
        if abs(m)==1:
            return inverse(matrix)
        if abs(m)%2==0:
            return inverse(multiply(exponentOfMatrix(matrix,m//2),exponentOfMatrix(matrix,m//2)))
        if abs(m)%2!=0:
            return inverse(multiply(exponentOfMatrix(matrix,(m-1)/2),exponentOfMatrix(matrix,(m+1)/2)))
    else:
        if m==0:
            return [[1 for i in range(len(matrix))] for j in range(matrix[0])]
        if m==1:
            return matrix
        if m%2==0:
            return multiply(exponentOfMatrix(matrix,m//2),exponentOfMatrix(matrix,m//2))
        if m%2!=0:
            return multiply(exponentOfMatrix(matrix,(m-1)/2),exponentOfMatrix(matrix,(m+1)/2))
            
    

try:
    n=int(input("Enter the order of matrix: "))
    matrix=([ print("enter " +str(j)+"th row elements (use spaces between two elements)") 
             or [int(i) for i in input().split() ]  for j in range(n)])
    m=int(input("Enter the power "))
    answer=exponentOfMatrix(matrix,m)
    print(answer)
except:
    print("Invalid input given, please try again")


Enter the order of matrix: 3
enter 0th row elements (use spaces between two elements)
12 7 3
enter 1th row elements (use spaces between two elements)
4 5 6
enter 2th row elements (use spaces between two elements)
7 8 9
Enter the power 3
[[3623, 2906, 2382], [2396, 2043, 1800], [3842, 3258, 2853]]


______________________________________________________________________________________________________
______________________________________________________________________________________________________

In [113]:
#Code for Method 3:

hm={}
def multiply(A,B):
    ans = [[0 for i in range(len(B))] for j in range(len(A[0]))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                ans[i][j] += A[i][k] * B[k][j]
    return ans

def inverse(matrix):
    import numpy as np
    try:
        i=np.linalg.inv(matrix)
        return i
    except:
        print("Inverse of the given matrix not possible")


def exponentOfMatrix(matrix,m):
    if m<0:
        m=-1*m
        if abs(m) in hm:
            return inverse(hm[1*m])
        if abs(m)==1:
            return inverse(matrix)
        if abs(m)%2==0:
            hm[m]=(multiply(exponentOfMatrix(matrix,m//2),exponentOfMatrix(matrix,m//2)))
            return inverse(hm[m])
        if abs(m)%2!=0:
            hm[m]=multiply(exponentOfMatrix(matrix,(m-1)/2),exponentOfMatrix(matrix,(m+1)/2))
            return inverse(hm[m])
    else:
        if abs(m) in hm:
            return hm[m]
        if m==0:
            return [[1 for i in range(len(matrix))] for j in range(matrix[0])]
        if m==1:
            return matrix
        if m%2==0:
            hm[m]=multiply(exponentOfMatrix(matrix,m//2),exponentOfMatrix(matrix,m//2))
            return hm[m]
        if m%2!=0:
            hm[m]=multiply(exponentOfMatrix(matrix,(m-1)/2),exponentOfMatrix(matrix,(m+1)/2))
            return hm[m]
            
    

try:
    n=int(input("Enter the order of matrix: "))
    matrix=([ print("enter " +str(j)+"th row elements (use spaces between two elements)") 
             or [int(i) for i in input().split() ]  for j in range(n)])
    m=int(input("Enter the power "))
    answer=exponentOfMatrix(matrix,m)
    print(answer)
except:
    print("Invalid input given, please try again")


Enter the order of matrix: 3
enter 0th row elements (use spaces between two elements)
12 7 3
enter 1th row elements (use spaces between two elements)
4 5 6
enter 2th row elements (use spaces between two elements)
7 8 9
Enter the power -10
[[ -307.80428919 -4569.22576498  3139.78133209]
 [  687.73328403 10209.11257904 -7015.27627254]
 [ -370.85557447 -5505.19568869  3782.94081799]]


In [91]:
hm #to access other powers lower than m for the  matrix, we can see the given dictionary

{2.0: [[214, 167, 168], [110, 101, 108], [179, 161, 171]],
 3.0: [[4412, 3677, 3798], [2480, 2139, 2238], [3989, 3426, 3579]],
 5: [[2028480, 1719659, 1787790],
  [1166612, 990517, 1030350],
  [1871147, 1588408, 1652169]],
 10: [[9466123830838, 8031385300343, 8352078126360],
  [5449934439614, 4623914935397, 4808548787580],
  [8740091168099, 7415398362761, 7711496482491]]}

______________________________________________________________________________________________________
______________________________________________________________________________________________________

In [145]:
# Code for Method 4:
import numpy as np

def inverse(matrix):
    import numpy as np
    try:
        i=np.linalg.inv(matrix)
        return i
    except:
        print("Inverse of the given matrix not possible")

def multiply(A,B):
    ans = [[0 for i in range(len(B))] for j in range(len(A[0]))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                ans[i][j] += A[i][k] * B[k][j]
    return ans

def eigenvectorMatrix(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvectors
    
def diagnolMatrix(matrix,m):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    for i in range(len(eigenvalues)):
        eigenvalues[i]=eigenvalues[i]**m
    D=[[0 if i!=j else eigenvalues[j] for i in range(len(matrix))] for j in range(len(matrix))]
    return D

def exponentOfMatrix(matrix,m):
    V=eigenvectorMatrix(matrix)
    D=diagnolMatrix(matrix,m)
    Vinv=inverse(V)
    answer=multiply(V,multiply(D,Vinv))
    return answer

n=int(input("Enter the order of matrix: "))
matrix=([ print("enter " +str(j)+"th row elements (use spaces between two elements)") 
         or [int(i) for i in input().split() ]  for j in range(n)])
m=int(input("Enter the power "))
# matrix = np.asarray(matrix, dtype=np.float32)
answer=exponentOfMatrix(matrix,m)
print(answer)


Enter the order of matrix: 3
enter 0th row elements (use spaces between two elements)
12 7 3
enter 1th row elements (use spaces between two elements)
4 5 6
enter 2th row elements (use spaces between two elements)
7 8 9
Enter the power 3
[[3623.0000000000005, 2905.999999999998, 2381.9999999999986], [2395.9999999999986, 2042.999999999997, 1799.999999999998], [3841.9999999999977, 3257.999999999996, 2852.9999999999973]]
